version: '3.8'

services:
  php:
    build: ./php
    container_name: php-container
    ports:
      - "8080:80"
    volumes:
      - ./php/www:/var/www/html
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5    
    volumes:
      - ./mysql/bd:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - my-network

  node:
    build: ./node
    container_name: node-container
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - my-network
    depends_on:
      - mysql
      - php
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=your_database

networks:
  my-network:
    driver: bridge